CREATE TABLE short_urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    short_code VARCHAR(32) NOT NULL,
    original_url VARCHAR(2048) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    custom_alias BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_short_urls_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_short_urls_short_code UNIQUE (short_code),
    CONSTRAINT ck_short_urls_status
        CHECK (status IN ('ACTIVE', 'DISABLED', 'BLOCKED')),
    CONSTRAINT ck_short_urls_short_code
        CHECK (short_code ~ '^[A-Za-z0-9_-]{4,32}$'),
    CONSTRAINT ck_short_urls_original_url_not_blank
        CHECK (BTRIM(original_url) <> ''),
    CONSTRAINT ck_short_urls_expiration
        CHECK (expires_at IS NULL OR expires_at > created_at)
);

CREATE INDEX idx_short_urls_user_created_at
    ON short_urls (user_id, created_at DESC);

CREATE INDEX idx_short_urls_user_status
    ON short_urls (user_id, status);

CREATE INDEX idx_short_urls_expires_at
    ON short_urls (expires_at)
    WHERE expires_at IS NOT NULL;
