CREATE TABLE short_url_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    short_url_id BIGINT,
    short_code VARCHAR(32) NOT NULL,
    action VARCHAR(40) NOT NULL,
    details VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_short_url_audit_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_short_url_audit_short_url
        FOREIGN KEY (short_url_id) REFERENCES short_urls (id) ON DELETE SET NULL
);

CREATE INDEX idx_short_url_audit_user_created
    ON short_url_audit_events (user_id, created_at DESC, id DESC);
